version: "3"

services:
  web:
    build: ./
    volumes:
      - build:/app/build
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./dist:/www/web
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  build:

networks:
  default:
    external:
      name: the-pizza-task-be_nginx_network
